included:
  - WeatherDemoApp
excluded:
  - Pods

disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace


# configurable rules can be customized from this configuration file
# binary rules can set their severity level

# swift

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - force_unwrapping
  - first_where
  - literal_expression_end_indentation
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_over_fileprivate
  - redundant_nil_coalescing
  - redundant_type_annotation
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_declaration
  - unused_import
  - vertical_whitespace_closing_braces
  - yoda_condition
  - attributes

discouraged_object_literal: error
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
vertical_whitespace_closing_braces:
  severitty: warning
  validate_extensions: false

identifier_name:
  excluded:
    - id
    - x
    - y
    - z

attributes:
  always_on_same_line:
    - "@IBSegueAction"
    - "@IBAction"
    - "@NSManaged"
    - "@objc"

# formatting

trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true
#indentation_width:
#  indentation_width: 4
vertical_whitespace:
  max_empty_lines: 2
#line_length:
#  ignores_urls: true
#  ignores_function_declarations: true
#  ignores_comments: false
file_length:
  warning: 800
  error: 1500
function_body_length:
  warning: 80
  error: 200
type_body_length:
  warning: 400
  error: 500
large_tuple:
  warning: 3
  error: 5
#multiline_arguments:
#  first_argument_location: current_line
#  only_enforce_after_first_closure_on_first_line: true
type_name:
    min_length: 1
    max_length: 80

#warning_threshold: 1000

custom_rules:
  array_constructor:
    name: "Array/Dictionary initializer"
    regex: '[let,var] .+ = (\[.+\]\(\))'
    capture_group: 1
    message: "Use explicit type annotation when initializing empty arrays and dictionaries"
    severity: warning
